"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var express_1 = require("express");
var getHandlers_1 = require("../handlers/getHandlers");
var getRouter = (0, express_1.Router)();
getRouter.get('/persona', getHandlers_1.getUserHandler);
getRouter.get('/proyects', getHandlers_1.getProyectsHandler);
getRouter.get('/experiences', getHandlers_1.getExperienceHandler);
getRouter.get('/skill', getHandlers_1.getSkillsHandler);
getRouter.get('/social', getHandlers_1.getSocialHandler);
getRouter.get('/studies', getHandlers_1.getStudiesHandler);
exports.default = getRouter;
