"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var express_1 = require("express");
var getRoutes_1 = require("./getRoutes");
var postRoutes_1 = require("./postRoutes");
var updateRoutes_1 = require("./updateRoutes");
var deleteRoutes_1 = require("./deleteRoutes");
var mailerRoutes_1 = require("./mailerRoutes");
var mainRouter = (0, express_1.Router)();
mainRouter.use('/send_email', mailerRoutes_1.default);
mainRouter.use('/get', getRoutes_1.default);
mainRouter.use('/add', postRoutes_1.default);
mainRouter.use('/edit', updateRoutes_1.default);
mainRouter.use('/delete', deleteRoutes_1.default);
exports.default = mainRouter;
